# Generated by Django 5.1.1 on 2025-06-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_skipped_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='primaryBreed',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='secondaryBreed',
        ),
        migrations.AddField(
            model_name='dog',
            name='breeds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='selected_plan',
            field=models.CharField(choices=[('3mo', '3 Month'), ('6mo', '6 Month'), ('monthly', 'Monthly')], max_length=20),
        ),
    ]
